In [1]:
import polars as pl

In [13]:
GOLDEN_PATH = "../data/nq_open_gold/processed/train.feather"
WIKI_PATH = "../data/wiki_dump2018_nq_open/processed/wiki.feather"
train  = pl.read_ipc(GOLDEN_PATH)
wiki = pl.read_ipc(WIKI_PATH).with_row_index("idx")
train.head()

shape: (5, 5)
┌───────────────────┬───────────────────┬──────────────────┬───────────────────┬───────────────────┐
│ example_id        ┆ question          ┆ answers          ┆ text              ┆ idx_gold_in_corpu │
│ ---               ┆ ---               ┆ ---              ┆ ---               ┆ s                 │
│ i64               ┆ str               ┆ list[str]        ┆ str               ┆ ---               │
│                   ┆                   ┆                  ┆                   ┆ i64               │
╞═══════════════════╪═══════════════════╪══════════════════╪═══════════════════╪═══════════════════╡
│ -6802534628745605 ┆ total number of   ┆ ["2,718"]        ┆ As of June 14 ,   ┆ 20970735          │
│ 728               ┆ death row inma…   ┆                  ┆ 2018 , there w…   ┆                   │
│ -8178292525996414 ┆ big little lies   ┆ ["seven"]        ┆ Despite           ┆ 20970736          │
│ 464               ┆ season 2 how m…   ┆                  ┆ originally being  ┆                   │
│                   ┆                   ┆                  ┆ bille…            ┆                   │
│ 17277983450248463 ┆ who sang waiting  ┆ ["Foreigner"]    ┆ '' Waiting for a  ┆ 20970737          │
│ 17                ┆ for a girl li…    ┆                  ┆ Girl Like You…    ┆                   │
│ -1862942322519208 ┆ where do you      ┆ ["Saltfjellet"]  ┆ The Arctic circle ┆ 20970738          │
│ 465               ┆ cross the arctic  ┆                  ┆ crosses main…     ┆                   │
│                   ┆ …                 ┆                  ┆                   ┆                   │
│ -6742567993987506 ┆ who is the main   ┆ ["Sam - I - am"] ┆ A character named ┆ 20970739          │
│ 913               ┆ character in g…   ┆                  ┆ '' Sam - I -…     ┆                   │
└───────────────────┴───────────────────┴──────────────────┴───────────────────┴───────────────────┘

In [14]:
train.head()

shape: (5, 5)
┌───────────────────┬───────────────────┬──────────────────┬───────────────────┬───────────────────┐
│ example_id        ┆ question          ┆ answers          ┆ text              ┆ idx_gold_in_corpu │
│ ---               ┆ ---               ┆ ---              ┆ ---               ┆ s                 │
│ i64               ┆ str               ┆ list[str]        ┆ str               ┆ ---               │
│                   ┆                   ┆                  ┆                   ┆ i64               │
╞═══════════════════╪═══════════════════╪══════════════════╪═══════════════════╪═══════════════════╡
│ -6802534628745605 ┆ total number of   ┆ ["2,718"]        ┆ As of June 14 ,   ┆ 20970735          │
│ 728               ┆ death row inma…   ┆                  ┆ 2018 , there w…   ┆                   │
│ -8178292525996414 ┆ big little lies   ┆ ["seven"]        ┆ Despite           ┆ 20970736          │
│ 464               ┆ season 2 how m…   ┆                  ┆ originally being  ┆                   │
│                   ┆                   ┆                  ┆ bille…            ┆                   │
│ 17277983450248463 ┆ who sang waiting  ┆ ["Foreigner"]    ┆ '' Waiting for a  ┆ 20970737          │
│ 17                ┆ for a girl li…    ┆                  ┆ Girl Like You…    ┆                   │
│ -1862942322519208 ┆ where do you      ┆ ["Saltfjellet"]  ┆ The Arctic circle ┆ 20970738          │
│ 465               ┆ cross the arctic  ┆                  ┆ crosses main…     ┆                   │
│                   ┆ …                 ┆                  ┆                   ┆                   │
│ -6742567993987506 ┆ who is the main   ┆ ["Sam - I - am"] ┆ A character named ┆ 20970739          │
│ 913               ┆ character in g…   ┆                  ┆ '' Sam - I -…     ┆                   │
└───────────────────┴───────────────────┴──────────────────┴───────────────────┴───────────────────┘

In [15]:
wiki.head()

shape: (5, 3)
┌─────┬─────────────────────────────────┬───────┐
│ idx ┆ text                            ┆ title │
│ --- ┆ ---                             ┆ ---   │
│ u32 ┆ str                             ┆ str   │
╞═════╪═════════════════════════════════╪═══════╡
│ 0   ┆ Aaron Aaron ( or ; "Ahärôn") i… ┆ Aaron │
│ 1   ┆ God at Sinai granted Aaron the… ┆ Aaron │
│ 2   ┆ his rod turn into a snake. The… ┆ Aaron │
│ 3   ┆ however, Aaron and Hur remaine… ┆ Aaron │
│ 4   ┆ Aaron and his sons to the prie… ┆ Aaron │
└─────┴─────────────────────────────────┴───────┘

In [12]:
## 1 - Release movie date
## 2 - Historical interesets
# 3 - Historical Figure (inventor of item)
## Concept of subject
## Number of things
## Location

selected_ids = [
    4393532674001821363	,
    -4144729966148354479,
    1317425899790858647,
    824576888464737344,
    -8930591693474034237,
    -1245842872065838644
]


train.filter(pl.col("example_id").is_in(selected_ids))

shape: (6, 5)
┌───────────────────┬───────────────────┬───────────────────┬───────────────────┬──────────────────┐
│ example_id        ┆ question          ┆ answers           ┆ text              ┆ idx_gold_in_corp │
│ ---               ┆ ---               ┆ ---               ┆ ---               ┆ us               │
│ i64               ┆ str               ┆ list[str]         ┆ str               ┆ ---              │
│                   ┆                   ┆                   ┆                   ┆ i64              │
╞═══════════════════╪═══════════════════╪═══════════════════╪═══════════════════╪══════════════════╡
│ -4144729966148354 ┆ why was there so  ┆ ["sugar markets"] ┆ After the         ┆ 20970748         │
│ 479               ┆ much interest…    ┆                   ┆ American Civil    ┆                  │
│                   ┆                   ┆                   ┆ War a…            ┆                  │
│ 13174258997908586 ┆ who developed the ┆ ["Dmitri          ┆ The Russian       ┆ 20970755         │
│ 47                ┆ first period…     ┆ Mendeleev"]       ┆ chemist Dmitri    ┆                  │
│                   ┆                   ┆                   ┆ Men…              ┆                  │
│ 43935326740018213 ┆ when did the who  ┆ ["Feb 7 , 2010"]  ┆ XLIV Date : Feb 7 ┆ 20970820         │
│ 63                ┆ perform at th…    ┆                   ┆ , 2010 Locat…     ┆                  │
│ 82457688846473734 ┆ the organization  ┆ ["composition"]   ┆ In the visual     ┆ 20970864         │
│ 4                 ┆ of the formal…    ┆                   ┆ arts , compositi… ┆                  │
│ -8930591693474034 ┆ how many          ┆ ["645"]           ┆ This is a list of ┆ 20971351         │
│ 237               ┆ scheduled tribes  ┆                   ┆ Scheduled Tr…     ┆                  │
│                   ┆ are …             ┆                   ┆                   ┆                  │
│ -1245842872065838 ┆ where did the     ┆ ["the Tuileries   ┆ During the reign  ┆ 20971524         │
│ 644               ┆ french king live… ┆ Palace"]          ┆ of Louis XIV …    ┆                  │
└───────────────────┴───────────────────┴───────────────────┴───────────────────┴──────────────────┘

In [8]:
wiki.filter(pl.col("id")==20970748).select("text").to_numpy()

array([['In this case, the number one position would place the member as the center on the single. The election result was revealed at the Balai Sarbini, South Jakarta on 22 April 2017 and broadcast live on RTV. The event was emceed by , who had been emceed the same event twice, and . The top 16 members were featured in JKT48\'s 17th single, "Indahnya Senyum Manismu..." and the members ranked 17 to 32 sang the B-side "Sedikit Saja I Love You!"; the recording was released in music card on 8 June 2017 and in CD-DVD on 4 August 2017. The']],
      dtype=object)

## Filter IDs - Get ids from the same document of Gold reference

In [23]:
gold_ids_in_corpus = (
    train
    .filter(pl.col("example_id").is_in(selected_ids))
    .select(pl.col("idx_gold_in_corpus").alias("idx"))
)

filter_wiki_titles= (
    wiki
    .join(gold_ids_in_corpus, on="idx", how="inner")
    .select("idx", "title")
)

sample_docs_from_gold = (
    wiki
    .join(filter_wiki_titles, on="title", how="inner")
    .join(filter_wiki_titles, on="idx", how="anti")
    .group_by("title")
    .agg(pl.col("idx").sample(n=4, shuffle=True, seed=42))
    
)

In [28]:
sample_docs_from_gold.to_numpy()

array([['History of the periodic table',
        array([21021886,  3037814,  3037817,  3037823], dtype=uint32)],
       ['Tuileries Palace',
        array([2885373, 2885396, 2885377, 2885390], dtype=uint32)],
       ['Composition (visual arts)',
        array([5022625, 5022643, 5022628, 5022634], dtype=uint32)],
       ['List of Super Bowl halftime shows',
        array([21030529, 21000837, 21018761, 21017044], dtype=uint32)],
       ['Spanish-American War',
        array([21031011, 20987163, 21018302, 21014051], dtype=uint32)]],
      dtype=object)